name: schulportal_hessen_app
description: A new Flutter application.
authors:
  - Samir Karaouan
  - Joshua Hatzinger
  - Maximilian Wabbels

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 99.99.99+99

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  html_character_entities: ^1.0.0+1
  html: ^0.15.0
  http: ^0.13.1
  uuid: ^3.0.3
  basic_utils: ^3.0.0-nullsafety.3
  simple_rsa: 0.0.5
  dio: ^4.0.0
  tuple: ^2.0.0
  encrypt: ^5.0.0
  school_ui_toolkit: 5.0.0
  crypton: ^2.0.1
  flutter_local_notifications: ^5.0.0
  flutter_secure_storage: ^4.1.0
  flutter_launcher_icons: ^0.9.0
  flutter_downloader: ^1.5.2
  font_awesome_flutter: ^8.11.0
  navigation_history_observer: ^1.0.3+1
  flutter_cache_manager: ^2.1.1
  expandable: ^5.0.1
  flutter_html: ^2.0.0-nullsafety.0
  ext_storage: ^1.0.3
  permission_handler: ^6.1.1
  flutter_svg: ^0.21.0-nullsafety.0
  fluentui_system_icons: ^1.1.112
  badges: ^1.2.0
  dropdown_formfield: ^0.1.3
  searchable_dropdown: ^1.1.3
  local_auth: ^0.6.3+4
  angles: ^2.1.0
  cool_alert: ^1.0.1



flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  build_runner: ^1.12.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
